### ISSUE TITLE
Feature Request: Option to ignore corrupt lines instead of SyntaxError?

### ISSUE THREAD

**Issue by ashander** [mbostock/ndjson-cli#16]
With the file `demo.json` (contents below) which has some lines that are incomplete /malformed json, `ndjson-cat` raises an error:
 
```sh
 $ ndjson-cat  demo.json 
demo.json: SyntaxError: Unexpected token a
```
Would it be worthwhile to add this feature as an option to `ndjsonfilter` (or is it already possible there?)?.

```sh
# demo.json
aofa": 1}
{"five": 1}
{"wa
```

**Comment by mbostock** [comment]
ndjson-cat takes JSON as input, not newline-delimited JSON; its purpose is to convert zero or more JSON sources into a newline-delimited JSON stream.

I could maybe see a new ndjson-ignore program that silently drops invalid JSON input from an NDJSON stream, sort of like ndjson-filter, but instead of having a configurable filter it only outputs input objects that are valid JSON. But… I’m not really sure this is a good idea to include in the core suite, since it encourages you to ignore malformed input.

**Comment by ashander** [comment]
Thanks. I misunderstood the (clearly stated) purpose of `ndjosn-cat`. Given the rest of the suite is set up to work with clean JSON from there or elsewhere I see your point. If users want to ignore some malformed lines in NDJSON files, they can write their own filter to do so (and hopefully think carefully about what type of malformation is OK to ignore).
